### ISSUE TITLE
Still working? Shows as unavailable

### ISSUE THREAD

**Issue by Xitro01** [marlub/philips-airpurifier#1]
Hi,

Is this add-on still working? I installed it through HACS and put in the example configuration with the right IP address but the entity shows as "unavailable".

Any ideas?

Thanks in advance!

**Comment by marlub** [comment]
Whats your airpurifier model? Because this repo only supports http models and not coap.

It is still working fine for my AC3829/10.

Do you have any log entries?

**Comment by Xitro01** [comment]
> Whats your airpurifier model? Because this repo only supports http models and not coap.
> 
> It is still working fine for my AC3829/10.
> 
> Do you have any log entries?

I have the exact same model. I am using this one now: https://github.com/betaboon/philips-airpurifier-coap
That one had some strange issues with not appearing as well, but seems to work consistently now.

Maybe these devices are very slow at start. Probably just the behaviour of these devices, that's why I asked this question, wasn't sure if it was me or that HA changed something to break this add-on.

**Comment by marlub** [comment]
Sounds like your model is a coap one. There are different revisions from same model. You must look for coap repositories. There are a lot forks from betaboons one. Maybe one of them is working without issues.

**Comment by Xitro01** [comment]
> Sounds like your model is a coap one. There are different revisions from same model. You must look for coap repositories. There are a lot forks from betaboons one. Maybe one of them is working without issues.

Strange that there are such big differences between the same devices. My air purifier is fairly new, so maybe they updated the protocols on it before it shipped out. But why wouldn't yours get a software update for this?

Thanks for your information.
